### PR TITLE
Fix edit expired bug

### LINKED ISSUE #178: Can directly edit expired status bug
image

If this is the command: edit 1 s/completed,

No error is thrown.

### LINKED ISSUE #186: Tasks with same name, date, desc, but diff tags should be duplicate tasks

### PR DESCRIPTION
**Pull request by hengyongming**

### CODE REVIEW

**Review by khiaxeng — APPROVED** [review]
LGTM

File: src/main/java/seedu/taskify/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -83,6 +84,10 @@ public CommandResult execute(Model model) throws CommandException {
             throw new CommandException(MESSAGE_DUPLICATE_TASK);
         }
 
+        if (taskToEdit.getStatus().toString().equals("Expired")) {
+            throw new CommandException(MESSAGE_CANNOT_EDIT_EXPIRED_STATUS);
+        }
+
```
Comment (CSmortal) [inline src/main/java/seedu/taskify/logic/commands/EditCommand.java:90]: I think `.getStatus().toString()` is a violation of Law of Demeter

Comment (CSmortal) [reply src/main/java/seedu/taskify/logic/commands/EditCommand.java:90]: It might not since all objects have `toString`, but since `Status` has an overriden `toString`, it might be a violation. Not 100% sure

**Review by noelmathewisaac — APPROVED** [review]

**Review by CSmortal — CHANGES_REQUESTED** [review]
I think for EditCommand line 87, you could just use `taskToEdit.getStatus().equals(new Status(StatusType.EXPIRED))`
